### ISSUE TITLE
Trying to create a virtualenv in windows

### ISSUE THREAD

**Issue by JoelSantosRico** [johnbeard/kiplot#7]
Hi!

I'm trying to create a virtualenv for KiPlot as I understand it's the easiest way to get it running because of the problems of "nomal" python to find the pcbnew module. I run this

``` bash
C:\Users\Joel\Workspace>virtualenv --python "C:\Program Files\KiCad\bin\python.exe" --system-site-packages KiPlot$ virtualenv --python /C/Program\ Files/KiCad/bin/python --system-site-packages ~/KiPlot
Running virtualenv with interpreter C:/Program Files/KiCad/bin/python.exe
  No LICENSE.txt / LICENSE found in source
New python executable in C:/Users/Joel/Workspace/KiPlot/Scripts/python.exe
Traceback (most recent call last):
  File "C:/Users/Joel/Workspace/KiPlot/lib/python2.7/site.py", line 791, in <module>
    main()
  File "C:/Users/Joel/Workspace/KiPlot/lib/python2.7/site.py", line 779, in main
    aliasmbcs()
  File "C:/Users/Joel/Workspace/KiPlot/lib/python2.7/site.py", line 516, in aliasmbcs
    import locale, codecs
  File "C:/Users/Joel/Workspace/KiPlot/lib/python2.7/locale.py", line 17, in <module>
    import functools
ImportError: No module named functools
ERROR: The executable C:/Users/Joel/Workspace/KiPlot/Scripts/python.exe is not functioning
ERROR: It thinks sys.prefix is u'c:/users/joel/workspace' (should be u'c:/users/joel/workspace/kiplot')
ERROR: virtualenv is not compatible with this system or executable
Note: some Windows users have reported this error when they installed Python for "Only this user" or have multiple versions of Python installed. Copying the appropriate PythonXX.dll to the virtualenv Scripts/ directory may fix this problem.
```
I tried on MinGW and got the same result. Copying a Python27.dll to the suggested path doesn't help.

Can you help me to get the virtualenv installed?

Thanks!

**Comment by johnbeard** [comment]
Sorry, I have very little idea of how this stuff works on Windows.

**Comment by JoelSantosRico** [comment]
I gave up and ended up using WSL, but thanks anyway.
